### ISSUE TITLE
Broken links for images in doc

### ISSUE THREAD

**Issue by willingc** [GeneralSarsby/mjs_plot#10]
@GeneralSarsby Cool project. I noticed that images were not rendering here: http://generalsarsby.github.io/mjs_plot/docs.html#demos

**Comment by GeneralSarsby** [comment]
Thanks, I'm on it. The docs.html page is a little out of date

**Comment by GeneralSarsby** [comment]
I've fixed the images, including the links to the cheat sheets.
But that whole page would benefit from a lot more of my attention.

**Comment by willingc** [comment]
You missed one tiny image in Quickstart 11. OpenStack has some good tips in their docs contributor guide http://docs.openstack.org/contributor-guide/index.html

Good luck with the project :cake:

**Comment by GeneralSarsby** [comment]
Opps, I've caught that one too. 

Thanks for the link, I'll give it a good read.
